# Generated by Django 5.2.8 on 2025-11-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascoteros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascoteros.dueño')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascoteros.mascota')),
            ],
        ),
        migrations.DeleteModel(
            name='Estadía',
        ),
    ]
