# Generated by Django 5.2.8 on 2025-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascoteros', '0002_estadia_delete_estadía'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadia',
            old_name='fecha_ingreso',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='estadia',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='estadia',
            name='fecha_inicio',
            field=models.DateField(default='2025-12-01'),
            preserve_default=False,
        ),
    ]
